name = "Camadkins"
license = "MIT"
licenselink = ""
description = "Quiet Signal â€” a minimal Hugo theme"
tags = ["minimal", "personal", "blog"]
min_version = "0.128.0"

[author]
  name = "Cam Adkins"
  homepage = "https://camadkins.com"
